baseurl = "//moodley.netlify.app"
languageCode = "en-us"
title = "Tyrone Moodley"
theme = "hugo-strata-theme"
disqusShortname = "tymoodley"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Tyrone Moodley"
	description = "I am Tyrone Moodley - Senior Full Stack Developer"

	# Format dates with Go's time formatting
	date_format = "2018-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "Hi, I am Tyrone Moodley<br>Senior Full Stack Developer"
		# The icons will be shown if you enter your username
		twitter = "tmoodley"
		github = "tmoodley"
		dribbble = ""
		facebook = "tyrone.moodley"
		googleplus = "TyMoodley"
		flickr = ""
		linkedin = "tyronemoodley"

		copyright = [
			"&copy; Tyrone Moodley",
			"Design: [MOODLEY](//moodley.ca)",
			"Demo Images: [Unsplash](//unsplash.com/)"
		]


	[params.about]
		hide  = false
		title = "ASP.Net Full Stack Developer, Blogger, Father, Husband, Son, Brother."
		content = "Senior .Net Developer at Waterloo's most innovative Software Development firm. Works on a SaaS application. Fullstack engineer working with ASP.NET MVC, Angular 2, Front end technologies like CSS, Javascript, AngularJS, VueJS."

 

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "Contact me."

		address = [ 
			"Waterloo, ON",
			"Canada"
		]
		phone = "647-933-1469"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "ty.moodley@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar 

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 10
